CONFIG_BOARD_FLASH_SIZE := 2


CONFIG_BL_IOT_FW_AP := 1
CONFIG_BL_IOT_FW_AMPDU := 0
CONFIG_BL_IOT_FW_AMSDU := 0
CONFIG_BL_IOT_FW_P2P := 0
CONFIG_ENABLE_PSM_RAM := 1
CONFIG_ENABLE_VFS_ROMFS := 1

CONFIG_ENABLE_PSM_EF_SIZE := 16K

CONFIG_FREERTOS_TICKLESS_MODE := 0

CONFIG_BT := 0

CONFIG_LWIP_IPV6 := y
CONFIG_LWIP_IPV6_AUTOCONFIG := y

LOG_ENABLED_COMPONENTS := blog_testc hal_drv loopset looprt bloop
CONFIG_LWIP_DHCP := y
CONFIG_LWIP_DHCPD := y
CONFIG_LWIP_AUTOIP := n

